### ISSUE TITLE
Finished setting up Ganache and Truffle but still no test fails even though they should

### ISSUE THREAD

**Issue by marius1909** [internet-sicherheit/proof-of-visit-dapp#3]
Still having to find out whats wrong. I use example Contracts that come with truffle. I can connect to my Ganache blockchain but still every test passes.

**Comment by kiview** [comment]
I am getting output

```
  TestTokenManager
    ✓ testTotalSupply (170ms)
    1) testTotalSupplyLocations
    > No events were emitted
    ✓ testOwnerOf (139ms)


  2 passing (6s)
  1 failing

  1) TestTokenManager
       testTotalSupplyLocations:
     Error: It should be 1 location in array  (Tested: 0, Against: 99)
      at checkResultForFailure (/home/kwittek/.nvm/versions/node/v14.0.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/soliditytest.js:68:1)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Context.<anonymous> (/home/kwittek/.nvm/versions/node/v14.0.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/soliditytest.js:94:1)
```

What are you expecting?

**Comment by kiview** [comment]
So @marius1909 said it behaves differently on his system, so it might be Windows related?

**Comment by marius1909** [comment]
Yes it is a windows problem, will install linux now.
